CREATE DATABASE PizzaDb


CREATE TABLE Users(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Firstname NVARCHAR(100) NOT NULL,
Lastname NVARCHAR(200) NOT NULL,
[Address] NVARCHAR(250) NOT NULL,
PhoneNumber NVARCHAR(50) NOT NULL
)

CREATE TABLE Orders(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IsDelivered BIT NOT NULL,
Price DECIMAL(18,2) NOT NULL,
UserId INT NOT NULL
)

CREATE TABLE Pizzas(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Name] NVARCHAR(200) NOT NULL,
Price DECIMAL(18,2) NOT NULL,
PizzaSizeId INT NOT NULL,
OrderId INT NOT NULL
)

CREATE TABLE PizzaSizes(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Name] NVARCHAR(200) NOT NULL
)


CREATE TABLE Toppings(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Name] NVARCHAR(200) NOT NULL,
Price DECIMAL(18,2) NOT NULL
)


CREATE TABLE PizzaToppings(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
PizzaId INT NOT NULL,
ToppingId INT NOT NULL
)


ALTER TABLE Orders 
ADD CONSTRAINT FK_Orders_Users
FOREIGN KEY (UserId) REFERENCES Users(Id)

ALTER TABLE Pizzas
ADD CONSTRAINT FK_Pizzas_Orders
FOREIGN KEY (OrderId) REFERENCES Orders(Id)

ALTER TABLE Pizzas
ADD CONSTRAINT FK_Pizzas_PizzaSizes
FOREIGN KEY (PizzaSizeId) REFERENCES PizzaSizes(Id)


ALTER TABLE PizzaToppings
ADD CONSTRAINT FK_PizzaToppings_Pizzas
FOREIGN KEY (PizzaId) REFERENCES Pizzas(Id)

ALTER TABLE PizzaToppings
ADD CONSTRAINT FK_PizzaToppings_Toppings
FOREIGN KEY (ToppingId) REFERENCES Toppings(Id)